{% set name = "pystencils-walberla" %}
{% set version = "0.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pystencils_walberla-{{ version }}.tar.gz
  sha256: 966389da6cc2b134d7f5676a76dd35328d8b0ee5b0d8a6627a39cfae971204cb

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jinja2
    - pystencils
    - python >={{ python_min }}

test:
  imports:
    - pystencils_walberla
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://i10git.cs.fau.de/pycodegen/pystencils_walberla
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.txt
  summary: 'Formulate stencil kernels in pystencils and generate optimized C++ Code for waLBerla from it.'
  description: |
    Formulate stencil kernels in pystencils and generate optimized C++ 
    Code for waLBerla from it. Look at the waLBerla documentation on how 
    to use it.
  doc_url: https://i10git.cs.fau.de/pycodegen/pystencils_walberla
  dev_url: https://i10git.cs.fau.de/pycodegen/pystencils_walberla

extra:
  recipe-maintainers:
    - jan-janssen
